build:
  package:
    image: etap
    volumes:
      - /packages/etap:/packages
    commands:
      - id
      - apt-get update
      - apt-get install build-essential equivs devscripts
      - mkdir -p build-area
      - cd build-area
      - dpkg-source -x /packages/$(basename $DRONE_REPO)/*.dsc build-$(basename $DRONE_REPO)
      - cd build-$(basename $DRONE_REPO)
      - mk-build-deps -i -r
      - dpkg-buildpackage -b -uc
      - cd ..
      - cp  -vt /packages/$(basename $DRONE_REPO) *.udeb *.deb *.changes 2>/dev/null || true
  test:
    image: etap
    volumes:
      - /packages/etap:/packages
    commands:
      - id
      - apt-get update
      - dpkg -i /packages/$(basename $DRONE_REPO)/*.deb || apt-get install -f
      - dpkg -i /packages/$(basename $DRONE_REPO)/*.deb
      - echo "DONE"
branches:
  - master
